name: Build and Deploy to MicroK8s

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.19.0'  # Versão compatível com o MicroK8s

      - name: Configure kubeconfig for MicroK8s
        run: |
          mkdir -p ~/.kube
          echo "$MICROK8S_KUBECONFIG_CONTENT" > ~/.kube/config
          # Certifique-se de substituir "$MICROK8S_KUBECONFIG_CONTENT" com seu kubeconfig do MicroK8s

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ./k8s/deployment.yaml
