name: Construção da imagem Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Atualizado para usar Node.js 20

    - name: Build and push Docker image
      uses: docker/build-push-action@v3.2.0
      with:
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/my-home-cicd:v1
          ${{ secrets.DOCKER_USERNAME }}/my-home-cicd:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Atualizado para usar Node.js 20

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3  # Atualizado para garantir compatibilidade

    - name: Deploy to Kubernetes
      run: |
        microk8s kubectl apply -f k8s/deployment.yaml
